import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                //js
                "resources/js/app.js",
                "resources/js/config.js",
                "resources/js/pages/dashboard.js",
                "resources/js/pages/calendar.js",
                "resources/js/pages/auth-two-factor.js",
                "resources/js/pages/auth-password.js",
                "resources/js/pages/chart-area.js",
                "resources/js/pages/chart-other.js",
                "resources/js/pages/chart-bar.js",
                "resources/js/pages/chart-line.js",
                "resources/js/pages/form-fileupload.js",
                "resources/js/pages/form-typehead.js",
                "resources/js/pages/form-choice.js",
                "resources/js/pages/form-quilljs.js",
                "resources/js/pages/form-wizard.js",
                "resources/js/maps/leaflet-data.js",
                "resources/js/pages/maps-leaflet.js",
                "resources/js/maps/world-merc.js",
                "resources/js/maps/world.js",
                "resources/js/maps/in-mill-en.js",
                "resources/js/maps/canada.js",
                "resources/js/maps/iraq.js",
                "resources/js/maps/russia.js",
                "resources/js/maps/spain.js",
                "resources/js/maps/us-aea-en.js",
                "resources/js/maps/us-lcc-en.js",
                "resources/js/maps/us-mill-en.js",
                "resources/js/pages/maps-vector.js",
                "resources/js/pages/datatables-ajax.js",
                "resources/js/pages/datatables-basic.js",
                "resources/js/pages/datatables-child-rows.js",
                "resources/js/pages/datatables-checkbox-select.js",
                "resources/js/pages/datatables-show-hide-columns.js",
                "resources/js/pages/datatables-export-data.js",
                "resources/js/pages/datatables-rendering.js",
                "resources/js/pages/flags-listing.js",
                "resources/js/pages/datatables-javascript-source.js",
                "resources/js/pages/datatables-select.js",
                "resources/js/pages/ui-interactive.js",

                //css
                "resources/scss/app.scss",
                "node_modules/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css",
                "node_modules/datatables.net-select-bs5/css/select.bootstrap5.min.css",
                "node_modules/datatables.net-bs5/css/dataTables.bootstrap5.min.css",
                "node_modules/dropzone/dist/dropzone.css",
                "node_modules/quill/dist/quill.bubble.css",
                "node_modules/quill/dist/quill.core.css",
                "node_modules/quill/dist/quill.snow.css",
                "node_modules/leaflet/dist/leaflet.css",
                "node_modules/jsvectormap/dist/jsvectormap.min.css",
            ],
            refresh: true,
        }),
    ],
});
